### ISSUE TITLE
Buoyancy Main checklist

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/buoyancy#1]
# Buoyancy master checklist

## Design
- [x] **Sim folder and design doc created** (Date: 05/16/2018)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed** [suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821)
   - [x] *If a Port:* Unfuddle tickets reviewed ([searching tickets](https://github.com/phetsims/phet-info/blob/master/issue-info/unfuddle-ticket-search.md))
- [x] **Learning goals and standards identified** (Date: 08/31/2018)
- [x] **Design concept complete**  (Date: 09/26/2018)
- [x] **Wireframes complete** (Date: 05/23/2019)
- [x] **Mockups complete** (Date: 08/31/2021)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: 05/14/2024)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: //)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional)
  - [ ] Screen-specific screenshots for metadata service (see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827))
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [x] Email announcement language
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [ ] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Make sim visible on website** 
   - [x] Clear "Metadata caches" on the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage) page
- [ ] **Post-publication items**
  - [ ] *If a Port:* Review legacy gold star activities, copy over if appropriate
  - [x] Share new features, design challenges, and treats with group!
  - [ ] Email announcement
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Create "sim primer" issue
  - [x] Hold postmortem if applicable (Date: //)

## Implementation
- [x] **Repository created** (Date: 4/23/2019)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 4/23/2019)
- [ ] **QA team "first look"** (Date: June 11th 2024)
- [ ] **Sim is "feature complete"** (Date: //)
- [x] **Code review completed** (Date: 8/31/2024)
- [ ] **Pre-publication items**
  - [ ] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks)
  - [ ] ~Add CT tests for public query parameters~
- [ ] **Published** (Date: //)
  - [ ] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Dev testing started** (Date: 6/18/24)
- [x] **Dev testing completed** (Date: 9/4/24)
- [x] **First RC published** (Date: 9/10/24)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 10/8/24)
