### ISSUE TITLE
Support Alt input and Interactive Highlights

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#76]

**Comment by AgustinVallejo** [comment]
Now supporting basic interactive highlights and keyboard nav. Will go into the specifics later.

I'll be looking at [this document](https://github.com/phetsims/phet-info/blob/main/doc/alternative-input-quickstart-guide.md) for better references on Alt Input

**Comment by AgustinVallejo** [comment]
Above commit added interactive highlights to mesh (Three.js) objects. I paired with @jessegreenberg to include it and we now have a basic square around mesh objects, and you can tab to them. If you use the a11y view, they even have a place and names in the PDOM when the Mass allows that (i.e. '1A', '1B').

Future work on this issue include:
- [x] Fix the Highlights shape around every mass (needs @jonathanolson)
- [x] See https://github.com/phetsims/density-buoyancy-common/issues/98 Consider using (Rich?)KeyboardDragListener to move blocks. (needs @jonathanolson)
- [x] see https://github.com/phetsims/buoyancy/issues/110 Decide on the blocks order on the PDOM
- [x] SEE https://github.com/phetsims/buoyancy/issues/109 Decide if UI elements are going to use accessible names
- [x] Address ghosts

**Comment by zepumph** [comment]
- [x] see https://github.com/phetsims/density-buoyancy-common/issues/99 Something to consider for interactive highlights is that we support "locked pointer" highlighting, when you click on a draggable and then drag off of it but are still dragging it. This is not currently supported for the masses. I'm unsure it has to be, but it seems worth a bit of investigation. 
- [ ] ~I also wonder, since we now have sorted out how to handle focus and highlights well for our specific case in Density/Buoyancy, if it is worth taking a look at mobius at all, to see if we could move this support in the THREE js "common code".~

**Comment by zepumph** [comment]
- [x] There is a bug about disposal since we added the focusablePath to MassView. It is failing CT. I found this over in https://github.com/phetsims/buoyancy/issues/96. I'll take a look. UPDATE: Looks like it is because linking the visibleProperties in the model/focus-view aren't cleaning up correctly. To be fixed in https://github.com/phetsims/buoyancy/issues/98

**Comment by zepumph** [comment]
We'll work on https://github.com/phetsims/density-buoyancy-common/issues/98 first.

**Comment by zepumph** [comment]
All further work here has been moved to side issues. TODO removed in these commits. Closing
