### ISSUE TITLE
PhET-iO initial dev implementation/review

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#86]
PhET-iO for Buoyancy is already quite far, but before continuing on https://github.com/phetsims/buoyancy/issues/51, it would be best to have the devs take a look through and see if there are any glaring issues with it. I think @AgustinVallejo and I are good candidates for this since he just went through two PhET-iO instrumentations in the last year and know the latest and greatest patterns. I'll label for both of us just to discuss the plan together, then we can sub-divide as needed.

**Comment by zepumph** [comment]
- [x] Use studio autoselect to determine what strings aren't currently instrumented, but should be.

**Comment by zepumph** [comment]
- [x] Ensure use of `simulationPreferences` instead of `simPreferences`. UPDATE There are 19 occurrences of `simPreferences` and 0 of `'simulationPreferences'`, and the documentation says: `// Content should create a child tandem called 'simPreferences'` https://github.com/phetsims/joist/issues/961#issue-2234152695

- [x] ~BlockSet tandemNames may want to be better names (with a noun): "sameMass". Perhaps "sameMassSet" since it is in the "blockSets" tandem.~
- [x] For B and B:B, naming blocks "block1A" instead of "blockA" in a set may be better to match the tag called "1A"
- [x] Alt input doesn't respect Mass.inputEnabledProperty
- [x] Don't show items that are not shown in screen (i.e. vectorScaleProperty) https://github.com/phetsims/density-buoyancy-common/issues/186
- [x] This doc is common code but specific to Density: https://github.com/phetsims/density-buoyancy-common/blob/57e8f323bff7bb3932b227739d10b4b97c7ca7f0/js/common/model/Mass.ts#L417-L419

**Comment by samreid** [comment]
- [x] I recommend moving the `model.liquidMaterialProperty`, `model.liquidDensityProperty` and `model.liquidViscosityProperty` into the `model.pool`. https://github.com/phetsims/buoyancy/issues/170
- [x] ~Likewise, perhaps `scale2` should become `pool.scale` and `scale1` should become `scale`.~ discuss in https://github.com/phetsims/buoyancy/issues/56

However, I was not confident enough to make this change without checking first.

**Comment by zepumph** [comment]
We are not yet done going through the compare screen model (screen one of buoyancy). Making progress though!

**Comment by samreid** [comment]
<details>

```diff

Subject: [PATCH] Fix memory leak, see https://github.com/phetsims/density-buoyancy-common/issues/123
---
Index: density-buoyancy-common/js/common/model/Mass.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/density-buoyancy-common/js/common/model/Mass.ts b/density-buoyancy-common/js/common/model/Mass.ts
--- a/density-buoyancy-common/js/common/model/Mass.ts	(revision e8ebe44f7c2bc0830930acdb155c6329d8ede99f)
+++ b/density-buoyancy-common/js/common/model/Mass.ts	(date 1718144121611)
@@ -21,7 +21,7 @@
 import { Shape } from '../../../../kite/js/imports.js';
 import EnumerationIO from '../../../../tandem/js/types/EnumerationIO.js';
 import optionize, { combineOptions } from '../../../../phet-core/js/optionize.js';
-import { Color, ColorProperty, PDOMValueType } from '../../../../scenery/js/imports.js';
+import { Color, ColorProperty, createGatedVisibleProperty, PDOMValueType } from '../../../../scenery/js/imports.js';
 import PhetioObject, { PhetioObjectOptions } from '../../../../tandem/js/PhetioObject.js';
 import Tandem from '../../../../tandem/js/Tandem.js';
 import BooleanIO from '../../../../tandem/js/types/BooleanIO.js';
@@ -83,7 +83,6 @@
   adjustableColor?: boolean;
   tag?: MassTag;
   accessibleName?: PDOMValueType | null;
-  phetioType?: IOType;
   inputEnabledPropertyOptions?: BooleanPropertyOptions;
   materialPropertyOptions?: PropertyOptions<Material>;
   volumePropertyOptions?: NumberPropertyOptions;
@@ -118,13 +117,13 @@
 
   public readonly userControlledProperty: Property<boolean>;
   public readonly inputEnabledProperty: Property<boolean>;
-  public readonly visibleProperty: TReadOnlyProperty<boolean>;
+
+  // This property is like a model value, indicating whether it should be shown
   public readonly internalVisibleProperty: Property<boolean>;
 
-  // Here just for instrumentation, see https://github.com/phetsims/density/issues/112
-  // This can only hide it, but won't make it visible.
-  // TODO: Definitely name it for "phet-io" and not "studio", https://github.com/phetsims/buoyancy/issues/51
-  private readonly studioVisibleProperty: Property<boolean>;
+  // There is a gated visibility property that is accessible to PhET-iO. Combined with the above internalVisibleProperty
+  // it yields this overall visibleProperty which is respected in the view.
+  public readonly visibleProperty: TReadOnlyProperty<boolean>;
 
   public readonly materialProperty: Property<Material>;
 
@@ -238,7 +237,8 @@
 
     super( options );
 
-    const tandem = options.tandem;
+    // TODO: Why did the question mark disappear? See https://github.com/phetsims/buoyancy/issues/86
+    const tandem: Tandem = options.tandem;
 
     this.engine = engine;
     this.body = options.body;
@@ -260,19 +260,11 @@
       phetioDocumentation: 'For internal use only',
 
       // instrumentation is needed for PhET-iO State only, not customizable.
-      tandem: tandem?.createTandem( 'internalVisibleProperty' ),
+      tandem: tandem.createTandem( 'internalVisibleProperty' ),
       phetioReadOnly: true
     } );
 
-    // REVIEW: This is very confusing, tandem names don't match
-    this.studioVisibleProperty = new BooleanProperty( true, {
-      tandem: tandem?.createTandem( 'visibleProperty' ),
-      phetioFeatured: true
-    } );
-
-    this.visibleProperty = DerivedProperty.and( [ this.internalVisibleProperty, this.studioVisibleProperty ], {
-      tandem: Tandem.OPT_OUT
-    } );
+    this.visibleProperty = createGatedVisibleProperty( this.internalVisibleProperty, tandem );
 
     this.materialProperty = new Property( options.material, combineOptions<PropertyOptions<Material>>( {
       valueType: Material,
@@ -683,7 +675,6 @@
 
     this.userControlledProperty.dispose();
     this.inputEnabledProperty.dispose();
-    this.studioVisibleProperty.dispose();
     this.materialProperty.dispose();
     this.volumeProperty.dispose();
     this.massProperty.dispose();
@@ -691,6 +682,7 @@
     this.buoyancyForceInterpolatedProperty.dispose();
     this.contactForceInterpolatedProperty.dispose();
     this.internalVisibleProperty.dispose();
+    this.visibleProperty.dispose();
     super.dispose();
   }
 
Index: scenery/js/util/createGatedVisibleProperty.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scenery/js/util/createGatedVisibleProperty.ts b/scenery/js/util/createGatedVisibleProperty.ts
--- a/scenery/js/util/createGatedVisibleProperty.ts	(revision 3eee1a1fbf33d3a1dd8abd1b59405fcb8adeff1f)
+++ b/scenery/js/util/createGatedVisibleProperty.ts	(date 1718144260750)
@@ -7,7 +7,6 @@
  * such as a studio or a PhET-iO client.
  *
  * @author Marla Schulz (PhET Interactive Simulations)
- *
  */
 
 import Tandem from '../../../tandem/js/Tandem.js';
@@ -19,14 +18,24 @@
 import { combineOptions } from '../../../phet-core/js/optionize.js';
 import { scenery } from '../imports.js';
 
-const createGatedVisibleProperty = ( visibleProperty: TReadOnlyProperty<boolean>, tandem: Tandem, selfVisiblePropertyOptions?: PhetioObjectOptions ): TReadOnlyProperty<boolean> => {
-  return DerivedProperty.and( [ visibleProperty, new BooleanProperty( true, combineOptions<PhetioObjectOptions>( {
+const createGatedVisibleProperty = ( providedVisibleProperty: TReadOnlyProperty<boolean>, tandem: Tandem, selfVisiblePropertyOptions?: PhetioObjectOptions ): TReadOnlyProperty<boolean> => {
+
+  const selfVisibleProperty = new BooleanProperty( true, combineOptions<PhetioObjectOptions>( {
     tandem: tandem.createTandem( 'selfVisibleProperty' ),
-    phetioFeatured: true
-  }, selfVisiblePropertyOptions ) ) ], {
+    phetioFeatured: true,
+    phetioDocumentation: 'Provides an additional way to toggle the visibility for the PhET-iO Element.'
+  }, selfVisiblePropertyOptions ) );
+
+  const visibleProperty = DerivedProperty.and( [ providedVisibleProperty, selfVisibleProperty ], {
     tandem: tandem.createTandem( 'visibleProperty' ),
-    phetioValueType: BooleanIO
+    phetioValueType: BooleanIO,
+    phetioDocumentation: `Whether the PhET-iO Element is visible, see ${selfVisibleProperty.tandem.name} for customization.`
   } );
+
+  // Remove the selfVisibleProperty from the PhET-iO registry
+  visibleProperty.disposeEmitter.addListener( () => selfVisibleProperty.dispose() );
+
+  return visibleProperty;
 };
 
 export default createGatedVisibleProperty;

**Comment by zepumph** [comment]
We just made it though the entire Buoyancy compare screen. WoO!

**Comment by zepumph** [comment]
We made it all the way to the application screen view today. Woo! All that is left is the applications screen, and the global items.

**Comment by zepumph** [comment]
Bug POV:
- [x] ~buoyancy.applicationsScreen.model.objects.bottle.nameProperty, change it, the text in the density accordion box still says "System A".~ @samreid says: Let's leave these separate so a client could say "Bottle" and "Bottle and Boat Together" or equivalent.
- [x] [bottle.displacementVolumeProperty doesn't do anything, is it only needed for boat? At least instrumented as such?](https://github.com/phetsims/buoyancy/issues/178)
- [x] buoyancy.applicationsScreen.view.bottleControlNode.visibleProperty doesn't hide "Material Inside"
- [x] Maybe buoyancy.applicationsScreen.view.customBottleDensityNumberControl needs a gated visibleProperty?
- [x] Rename `blocksRadioButtonGroup` => `blocksModeRadioButtonGroup`. Rename the classes, variables and tandems. 7+ occurrences

**Comment by zepumph** [comment]
We finished Buoyancy sim, even the global items. Next is to go through Buoyancy:Basics. We do not plan to go through Density here, but think that a design review will be valuable over in https://github.com/phetsims/buoyancy/issues/51

**Comment by samreid** [comment]
@AgustinVallejo and I finished up Buoyancy: Basics and added another item to the checkbox above.  So the review is complete and all work is tracked above, committed, or moved to a question in the google doc.

**Comment by samreid** [comment]
As far as I can tell, the checkboxes in this issue were addressed or moved to side issues. Can this be closed?

**Comment by zepumph** [comment]
Yes indeed! Good work team.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by zepumph** [comment]
Ahh! So sloppy. I searched just in DBC but there was another in scenery.
